name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install LLVM
      run: sudo apt-get install llvm-11-dev libclang-common-11-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
